environments:
  dev: {}
  stage: {}
  prod: {}

---

releases:
  - name: ngo-app
    namespace: default
    chart: .

    values:
      - values/common.yaml
      - values/{{ .Environment.Name }}.yaml
