replicaCount: 3

image:
  repository: nginx
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 80
  targetPort: 80

ingress:
  enabled: true
  className: nginx
  host: stage.ngo.local

resources:
  requests:
    cpu: "200m"
    memory: "128Mi"

  limits:
    cpu: "400m"
    memory: "256Mi"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

config:
  appName: "NGO Management System"
  appEnv: "Staging"
