apiVersion: v1
kind: Pod

metadata:
  name: rbac-test
  namespace: dev

spec:
  serviceAccountName: demo-sa

  containers:
  - name: kubectl
    image: bitnami/kubectl:latest
    command: ["sleep", "3600"]
