environments:
  dev: {}
  stage: {}
  prod: {}

---

releases:
  - name: database

    namespace: default

    chart: ..

    labels:
      app: database

    values:
      - ../values/common.yaml
      - ../values/{{ .Environment.Name }}.yaml
