apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "ngo-chart.fullname" . }}-config

  labels:
{{ include "ngo-chart.labels" . | indent 4 }}

data:
  APP_NAME: {{ .Values.config.appName | quote }}
  APP_ENV: {{ .Values.config.appEnv | quote }}
