apiVersion: rbac.authorization.k8s.io/v1
kind: Role

metadata:
  name: {{ include "ngo-chart.fullname" . }}-role

  labels:
{{ include "ngo-chart.labels" . | indent 4 }}

rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs:
    - get
    - list
    - watch
