apiVersion: v1
kind: Secret

metadata:
  name: {{ include "ngo-chart.fullname" . }}-secret

  labels:
{{ include "ngo-chart.labels" . | indent 4 }}

type: Opaque

data:
  DB_USER: {{ .Values.secret.dbUser | b64enc | quote }}
  DB_PASSWORD: {{ .Values.secret.dbPassword | b64enc | quote }}
  JWT_SECRET: {{ .Values.secret.jwtSecret | b64enc | quote }}
